version: '3.8'

services:
  otelcol:
    image: otel/opentelemetry-collector:0.145.0 # change to the latest version
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml # to load a custom configuration file from your working directory, mount the file as a volume
    ports:
      # - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the Collector
      # - 8889:8889 # Prometheus exporter metrics
      # - 13133:13133 # health_check extension
      # - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension
